### ISSUE TITLE
Connection time to wifi

### ISSUE THREAD

**Issue by joneyes** [richonguzman/LoRa_APRS_iGate#67]
With a wifi network defined, i find that the i-gate often doesn't connect and launches the hotspot too quickly.
I might have to reboot it a couple of times for it to establish connection to the defined network.
(on the previous version, where there were multiple AP's defined, i also found it would do a lap of them before successfully connecting)

Is there a setting in the code that defines this wait time that i can tweak and confirm it resolves the issue?

The new web interface is much easier to configure than doing it in VSC - thanks.

**Comment by richonguzman** [comment]
Hi,

when it achieves the wifi connection does it keeps connected?


could it be the router to slow?

**Comment by joneyes** [comment]
Hi Rich,
Yes, once connected it stays up.
My config here is a Draytek 2862 non wifi router, with 2x draytek AP902 access points, so not poor quality internet service provider supplied devices.

I am using  lilygo T3_v1.6 1
The behaviour appears to be consistent.
From a cold power up, it fails to connect to the wifi and launches the hotspot.
Pressing the reset button to cause a reboot, without removing power, it connects straight away at the reboot.
I can try and provide a video if you want?

Many thanks for the software! Developers such as you are much appreciated!

Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: "Ricardo Guzman (Richonguzman)" ***@***.***>
Date: 05/04/2024 13:01 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Jon Eyes ***@***.***>, Author ***@***.***>
Subject: Re: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)


Hi,

when it achieves the wifi connection does it keeps connected?

could it be the router to slow?

**Comment by richonguzman** [comment]
the solution is not very good, but what if it stays like it is?

when you reboot it connects right away...  does the AP reboots after a few mins to try to connect to wifi by its own ?

**Comment by joneyes** [comment]
Ok, let me remove power and try again.
Are you thinking it may reconnect when the auto AP times out through no client connection?



Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: "Ricardo Guzman (Richonguzman)" ***@***.***>
Date: 05/04/2024 17:40 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Jon Eyes ***@***.***>, Author ***@***.***>
Subject: Re: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)


the solution is not very good, but what if it stays like it is?

when you reboot it connects right away... does the AP reboots after a few mins to try to connect to wifi by its own ?

**Comment by joneyes** [comment]
I reset the auto AP to a 2 minute time out.
The Auto AP switches off, and it doesn't try to connect.
If I reboot it using the reset button, it fails the first time and then if I reboot it agaon using the reset button while the auto AP  is active, it connects straight away.

Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: Jon Eyes ***@***.***>
Date: 05/04/2024 17:47 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Subject: RE: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)

Ok, let me remove power and try again.
Are you thinking it may reconnect when the auto AP times out through no client connection?



Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: "Ricardo Guzman (Richonguzman)" ***@***.***>
Date: 05/04/2024 17:40 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Jon Eyes ***@***.***>, Author ***@***.***>
Subject: Re: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)


the solution is not very good, but what if it stays like it is?

when you reboot it connects right away... does the AP reboots after a few mins to try to connect to wifi by its own ?

**Comment by lachutm** [comment]
I experienced few times that after saving some settings on my iGate (Lilygo T3_v1.6 1) it won't connect to local WiFi. I have to connect to AP and reboot board, after that works fine.

**Comment by joneyes** [comment]
After discussing the issue with Andy GM0UDL today, he suggested setting the AP time to 0 to disable it, as others in his area have had success with that option.

 I've tried this tonight and the problem persists, except the AP doesn't start.
Rebooting the T3 again and it connects to wifi straight away.

Is this an issue peculiar to this hardware, as two of us have the same issue?



Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: KD9PKP ***@***.***>
Date: 14/04/2024 15:32 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Jon Eyes ***@***.***>, Author ***@***.***>
Subject: Re: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)


I experienced few times that after saving some settings on my iGate (Lilygo T3_v1.6 1) it won't connect to local WiFi. I have to connect to AP and reboot board, after that works fine.

**Comment by richonguzman** [comment]
sometimes the Wifi/Router won't allow to be reconnected right away.... so in this delta/time the boards does a complete process of all wifi available to connect and starts again to get finally connection.

sometimes works supper fast, sometimes not.

we were talking about having the AP being "killed" after configuration to only stay in the "keep on trying on the Wifis saved" and not get again into WIFI AP mode

**Comment by joneyes** [comment]
Yes.
However, even when the AP times out, it won't connect to the saved wifi unless the device is rebooted



Regards
Jon Eyes
Sent from my Galaxy



-------- Original message --------
From: "Ricardo Guzman (Richonguzman)" ***@***.***>
Date: 16/04/2024 06:51 (GMT+00:00)
To: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Jon Eyes ***@***.***>, Author ***@***.***>
Subject: Re: [richonguzman/LoRa_APRS_iGate] Connection time to wifi (Issue #67)


sometimes the Wifi/Router won't allow to be reconnected right away.... so in this delta/time the boards does a complete process of all wifi available to connect and starts again to get finally connection.

sometimes works supper fast, sometimes not.

we were talking about having the AP being "killed" after configuration to only stay in the "keep on trying on the Wifis saved" and not get again into WIFI AP mode

**Comment by richonguzman** [comment]
this should be solved with new code added recently

**Comment by joneyes** [comment]
Hi Rich,
I've upgraded to the latest version with a clean install - it's still the same.
